/*Seguridad*/
---------------------------------------------------------------------------------------------------------
--								       CREACION ROLES   											   --
---------------------------------------------------------------------------------------------------------

BEGIN; CREATE ROLE CLIENTE LOGIN; COMMIT;
BEGIN; CREATE ROLE EMPLEADO LOGIN; COMMIT;
BEGIN; CREATE ROLE OPERARIO LOGIN; COMMIT;
BEGIN; CREATE ROLE HORNERO LOGIN; COMMIT;
BEGIN; CREATE ROLE SUPERVISOR; COMMIT;

BEGIN; CREATE ROLE GERENTE LOGIN; COMMIT;
BEGIN; CREATE ROLE GERENTE_PLANTA LOGIN; COMMIT;
BEGIN; CREATE ROLE SECRETARIA LOGIN; COMMIT;

---------------------------------------------------------------------------------------------------------
--								      OTORGAR HERENCIA   											   --
---------------------------------------------------------------------------------------------------------

BEGIN; ALTER ROLE EMPLEADO INHERIT; COMMIT;
BEGIN; ALTER ROLE OPERARIO INHERIT; COMMIT;
BEGIN; ALTER ROLE GERENTE INHERIT; COMMIT;

---------------------------------------------------------------------------------------------------------
--								       CREACION USUARIOS   											   --
---------------------------------------------------------------------------------------------------------

--USUARIO MAESTRO
	CREATE USER DBA WITH PASSWORD 'ADMIN';


	BEGIN; CREATE USER María_González WITH PASSWORD '21474659'; COMMIT;  --1
	BEGIN; CREATE USER Ana_Romero_Tules WITH PASSWORD '18934567'; COMMIT; --2
	BEGIN; CREATE USER Daniel_Guerrero  WITH PASSWORD '20876543'; COMMIT; --3

	BEGIN; CREATE USER Carlos_Torres WITH PASSWORD '27748963'; COMMIT; --4
	BEGIN; CREATE USER Luis_Blanco WITH PASSWORD '27474666';COMMIT; --5
	BEGIN; CREATE USER Carolina_Sánchez WITH PASSWORD '27474665'; COMMIT; --6
	BEGIN; CREATE USER María_González_López WITH PASSWORD '27474667'; COMMIT; --7
	BEGIN; CREATE USER Luis_Blanco_Fernández WITH PASSWORD '27441986'; COMMIT; --8
	BEGIN; CREATE USER Carlos_Blanco WITH PASSWORD '27365666';COMMIT; --9
	BEGIN; CREATE USER María_González_Suarez WITH PASSWORD '27364666'; COMMIT; --10
	BEGIN; CREATE USER Yuritza_Castillo WITH PASSWORD '27363666'; COMMIT; --11
	BEGIN; CREATE USER Luis_Blanco_Gutierrez WITH PASSWORD  '27362666'; COMMIT;--12

	BEGIN; CREATE USER Marcello_Servitad WITH PASSWORD '25474658'; COMMIT;--13
	BEGIN; CREATE USER Valentina_Harrison WITH PASSWORD '24485673'; COMMIT;--14
	BEGIN; CREATE USER Alejandro_Guzmán WITH PASSWORD '26321549' ; COMMIT;--15
	BEGIN; CREATE USER Sandra_Mendoza WITH PASSWORD '24210987' ; COMMIT;--16

	BEGIN; CREATE USER Ana_Romero_Flores WITH PASSWORD '27403661' ; COMMIT;--17
	BEGIN; CREATE USER Pedro_González WITH PASSWORD '23254321' ; COMMIT;--18

	BEGIN; CREATE USER Ana_Romero WITH PASSWORD '24360661'; COMMIT; --19
	BEGIN; CREATE USER Luis_Muñoz WITH PASSWORD '25147362'; COMMIT;--20

	BEGIN; CREATE USER Ana_Romero_Turmero WITH PASSWORD '27474661'; COMMIT; --21
	BEGIN; CREATE USER Carlos_Blanco_Montoya WITH PASSWORD '23372615' ; COMMIT;--22

	BEGIN; CREATE USER Ana_Romero_Texan WITH PASSWORD '28568661' ; COMMIT; --23
	BEGIN; CREATE USER María_Gómez WITH PASSWORD '28261548'; COMMIT;--24

	BEGIN; CREATE USER Pedro_López WITH PASSWORD '28474660'  ; COMMIT;--25
	BEGIN; CREATE USER Gabriela_Martínez WITH PASSWORD '28251432'; COMMIT;--26
	BEGIN; CREATE USER Luis_Ramírez WITH PASSWORD '22548736' ; COMMIT;--27
	BEGIN; CREATE USER Andrea_Guerrero WITH PASSWORD '24721369' ; COMMIT;--28
	BEGIN; CREATE USER Carlos_Suárez WITH PASSWORD '23832147'; COMMIT;--29
	BEGIN; CREATE USER Isabel_Muñoz WITH PASSWORD '24943258' ; COMMIT; --30
	BEGIN; CREATE USER Daniel_Romero WITH PASSWORD '24054369'; COMMIT;--31
	BEGIN; CREATE USER Jennifer_Gómez WITH PASSWORD '24165470'; COMMIT;--32
	BEGIN; CREATE USER José_López WITH PASSWORD '24276581'; COMMIT;--33
	BEGIN; CREATE USER María_Ramírez WITH PASSWORD '24387692' ; COMMIT;--34

	BEGIN; CREATE USER Paco_Gutierrez WITH PASSWORD '24474670' ; COMMIT;--35
	BEGIN; CREATE USER Ana_Suárez WITH PASSWORD '24509815' ; COMMIT;--36
	BEGIN; CREATE USER Juan_Muñoz WITH PASSWORD '27474663' ; COMMIT;--37
	BEGIN; CREATE USER Gabriela_Pérez WITH PASSWORD '26362516' ; COMMIT;--38

	BEGIN; CREATE USER Luis_Gómez WITH PASSWORD  '27273645' ; COMMIT;--39
	BEGIN; CREATE USER Andrea_Blanco WITH PASSWORD '24184756'; COMMIT;--40

---------------------------------------------------------------------------------------------------------
--								       PRIVILEGIOS ROLES   											   --
---------------------------------------------------------------------------------------------------------
--                                     ROLES CON HERENCIA                                              --
--EMPLEADO
	BEGIN; GRANT SELECT ON DBA.DEPARTAMENTO TO EMPLEADO; COMMIT;
	BEGIN; GRANT SELECT ON DBA.DET_EXP TO EMPLEADO; COMMIT; 
	BEGIN; GRANT SELECT ON DBA.ESTADO_SALUD TO EMPLEADO; COMMIT; 
	BEGIN; GRANT SELECT ON DBA.EMPLEADO TO EMPLEADO; COMMIT;
	BEGIN; GRANT SELECT ON DBA.E_E TO EMPLEADO; COMMIT; 
	
	BEGIN; GRANT EMPLEADO TO OPERARIO, GERENTE; COMMIT;
	
--OPERARIO
	BEGIN; GRANT SELECT ON DBA.E_R TO OPERARIO; COMMIT;
	BEGIN; GRANT SELECT ON DBA.RESUMEN_REUNION TO OPERARIO; COMMIT; 
	
	BEGIN; GRANT OPERARIO TO HORNERO, SUPERVISOR; COMMIT;

--GERENTE
	BEGIN; GRANT SELECT ON DBA.DETALLE_PIEZA_VAJILLA TO GERENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.FAMILIAR_HISTORICO_PRECIO TO GERENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.PIEZA TO GERENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.VAJILLA TO GERENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.COLECCION TO GERENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.MOLDE TO GERENTE; COMMIT;
	
	BEGIN; GRANT GERENTE TO SECRETARIA, GERENTE_PLANTA; COMMIT;
	
---------------------------------------------------------------------------------------------------------
--                                     ROLES SIN HERENCIA                                              --

--CLIENTE
	BEGIN; GRANT SELECT ON DBA.CLIENTE TO CLIENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.PEDIDO TO CLIENTE; COMMIT;
	BEGIN; GRANT INSERT, SELECT ON DBA.PEDIDO TO CLIENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.FACTURA TO CLIENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.CONTRATO TO CLIENTE; COMMIT; 
	BEGIN; GRANT INSERT, SELECT ON DBA.DETALLE_PEDIDO_PIEZA TO CLIENTE; COMMIT;

	BEGIN; GRANT SELECT ON DBA.DETALLE_PIEZA_VAJILLA TO CLIENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.FAMILIAR_HISTORICO_PRECIO TO CLIENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.PIEZA TO CLIENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.VAJILLA TO CLIENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.COLECCION TO CLIENTE; COMMIT;
	BEGIN; GRANT SELECT ON DBA.MOLDE TO CLIENTE; COMMIT;
	
--HORNERO
	BEGIN; GRANT SELECT ON DBA.HORARIO TO HORNERO; COMMIT;
	
--SUPERVISOR
	BEGIN; GRANT INSERT ON DBA.RESUMEN_REUNION TO SUPERVISOR; COMMIT;
	BEGIN; GRANT INSERT ON DBA.E_R TO SUPERVISOR; COMMIT;
	BEGIN; GRANT INSERT ON DBA.DET_EXP TO SUPERVISOR; COMMIT;

--SECRETARIA
	BEGIN; GRANT INSERT, UPDATE() ON DBA.FACTURA TO SECRETARIA; COMMIT;
	

